/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i mystruct.h -c CarAdaptor -a car_adaptor_p.h:car_adaptor.cpp car.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CAR_ADAPTOR_P_H_1174440226
#define CAR_ADAPTOR_P_H_1174440226

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "mystruct.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.trolltech.Examples.CarInterface
 */
class CarAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.trolltech.Examples.CarInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.trolltech.Examples.CarInterface\" >\n"
"    <method name=\"accelerate\" />\n"
"    <method name=\"decelerate\" />\n"
"    <method name=\"turnLeft\" />\n"
"    <method name=\"turnRight\" />\n"
"    <method name=\"structer\" >\n"
"      <annotation value=\"MyStruct\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"      <arg direction=\"out\" type=\"(sxs)\" />\n"
"      <arg direction=\"out\" type=\"x\" />\n"
"    </method>\n"
"    <signal name=\"crashed\" />\n"
"  </interface>\n"
        "")
public:
    CarAdaptor(QObject *parent);
    virtual ~CarAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void accelerate();
    void decelerate();
    MyStruct structer(qlonglong &out1);
    void turnLeft();
    void turnRight();
Q_SIGNALS: // SIGNALS
    void crashed();
};

#endif
